"""
Django settings for tagaste project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os,site

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-bx&kj*zx+65tl0g4kl9o8$(t-&0_pki#r@kqi8lj+5ac)dmz@m'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'main'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'tagaste.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR,'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'main.context_processors.message_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'tagaste.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'churchdb',
        'USER':'postgres',
        'PASSWORD':'1234',
        'HOST':'localhost'
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Africa/Dar_es_Salaam'
USE_I18N = True
USE_L10N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_DIRS =[
     os.path.join(BASE_DIR, 'static'),
]


MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR,'media')
# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = 'ingia'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT=465
EMAIL_USE_SSL=True
EMAIL_HOST_USER="iammsacky@gmail.com"
EMAIL_HOST_PASSWORD="bhyw hdcz pkjo wbqv"

# Set token expiration time (in seconds)
PASSWORD_RESET_TIMEOUT = 3600  # 1 hour (3600 seconds)

AUTH_USER_MODEL = "main.CustomUser"

AUTHENTICATION_BACKENDS = [
    'main.backends.EmailAuthBackend',  # Custom email login
    'django.contrib.auth.backends.ModelBackend',  # Default username login
]

JAZZMIN_SETTINGS = {
    "site_title":"Admin",
    "site_brand":"MT. AMBROSI - TAGASTE",
    "site_header":"MT. AMBROSI - TAGASTE",
    "site_logo":"assets/images/71.jpeg",
    "site_logo_classes":"img-circle",
    "user_avatar":"assets/images/avatar.jpg",
    "welcome_sign":"Welcome to the Admin Panel",
    "copyright":"MT.AMBROSI-TAGASTE",
    "show_ui_builder":False,
    "icons": {
        "auth.Group": "fas fa-user-shield", 
        "main.Masomo":"fa-solid fa-book-open-reader",
        "main.Announcement":"fa-solid fa-bullhorn",
        "main.Viwawa":"fa-solid fa-bullhorn",
        "main.Uwaka":"fa-solid fa-bullhorn",
        "main.Wawata":"fa-solid fa-bullhorn",
        "main.Kanda":"fa-solid fa-people-group",
        "main.Event":"fa-solid fa-calendar-days",
        "main.Blog":"fa-solid fa-blog",
        "main.Sermon":"fa-solid fa-book-bible",
        "main.Article":"fa-solid fa-newspaper",
        "main.MakalaQuotation":"fa-solid fa-quote-left",
        "main.CarourselMatangazo":"fa-solid fa-image",
        "main.CarourselMatukio":"fa-solid fa-image",
        "main.CarourselRatiba":"fa-solid fa-image",
        "main.CarourselBlogu":"fa-solid fa-image",
        "main.CarourselMahubiri":"fa-solid fa-image",
        "main.CarourselMaktaba":"fa-solid fa-image",
        "main.CarourselJumuiya":"fa-solid fa-image",
        "main.CarourselUwaka":"fa-solid fa-image",
        "main.CarourselWawata":"fa-solid fa-image",
        "main.CarourselViwawa":"fa-solid fa-image",
        "main.CarourselVyama":"fa-solid fa-image",
        "main.Carourselkanda":"fa-solid fa-image",
        "main.CarourselUongozi":"fa-solid fa-image",
        "main.CarouselPodikasiti":"fa-solid fa-image",
        "main.Podcast":"fa-solid fa-podcast",
        "main.Give":"fa-solid fa-hand-holding-dollar",
        "main.Message":"fa-solid fa-message",
        "main.Mubashara":"fa-solid fa-video",
        "main.Library":"fa-solid fa-photo-film",
        "main.History":"fa-solid fa-timeline",
        "main.Faith":"fa-solid fa-cross",
        "main.Policy":"fa-solid fa-file-contract",
        "main.Rule":"fa-solid fa-scale-balanced",
        "main.Mapadri":"fa-solid fa-users",
        "main.Viongozi_wa_kanisani":"fa-solid fa-users",
        "main.Viongozi_wa_Jumuiya":"fa-solid fa-users",
        "main.Ubatizo":"fa-solid fa-dove",
        "main.Ndoa":"fa-solid fa-ring",
        "main.Ekaristi":"fa-solid fa-circle-half-stroke",
        "main.Kipaimara":"fa-solid fa-shield-halved",
        "main.Toba":"fa-solid fa-person-praying",
        "main.Upako_wa_Wagonjwa":"fa-solid fa-hands-praying",
        "main.Muda_wa_ibada":"fa-solid fa-clock",
        "main.Ratiba_za_ofisini":"fa-solid fa-clock",
        "main.Muda_wa_Maungamo":"fa-solid fa-clock",
        "main.Jumuiya":"fa-solid fa-people-group",
        "main.Jumuiya_page":"fa-solid fa-bullhorn",
        "main.Vyama_page":"fa-solid fa-bullhorn",
        "main.Kanda_page":"fa-solid fa-bullhorn",
        "main.Vyama":"fa-solid fa-people-group",
        "main.CustomUser":"fa-solid fa-user",
        "main.Resetpassword":"fa-solid fa-unlock-keyhole",
    },
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": True,
    "brand_small_text": False,
    "brand_colour": False,
    "accent": "accent-primary",
    "navbar": "navbar-white navbar-light",
    "no_navbar_border": False,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": True,
    "sidebar_nav_flat_style": False,
    "theme": "default",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}