# Generated by Django 5.1.6 on 2025-03-20 17:08

import django.db.models.deletion
import main.mixins
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.CharField(blank=True, editable=False, max_length=20, verbose_name='SIKU YA JUMA')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('matangazo', models.TextField(verbose_name='TANGAZO')),
            ],
            options={
                'verbose_name': 'MATANGAZO',
                'verbose_name_plural': 'MATANGAZO',
            },
            bases=(main.mixins.SwahiliDateMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picha', models.ImageField(upload_to='pics', verbose_name='PICHA')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('title', models.CharField(max_length=255, verbose_name='TITLE')),
                ('author', models.CharField(max_length=255, verbose_name='MWANDISHI')),
                ('maelezo', models.TextField(verbose_name='UJUMBE')),
            ],
            options={
                'verbose_name': 'MAKALA',
                'verbose_name_plural': 'MAKALA',
            },
            bases=(main.mixins.SwahiliDateMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picha', models.ImageField(upload_to='pics', verbose_name='PICHA')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('title', models.CharField(max_length=255, verbose_name='TITLE')),
                ('maelezo', models.TextField(verbose_name='UJUMBE')),
            ],
            options={
                'verbose_name': 'BLOGU',
                'verbose_name_plural': 'BLOGU',
            },
            bases=(main.mixins.SwahiliDateMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CarourselBlogu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picha', models.ImageField(upload_to='pics', verbose_name='PICHA')),
            ],
            options={
                'verbose_name': 'PICHA YA BLOGU',
                'verbose_name_plural': 'PICHA YA BLOGU',
            },
        ),
        migrations.CreateModel(
            name='CarourselJumuiya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picha', models.ImageField(upload_to='pics', verbose_name='PICHA')),
            ],
            options={
                'verbose_name': 'PICHA YA JUMUIYA ZETU',
                'verbose_name_plural': 'PICHA YA JUMUIYA ZETU',
            },
        ),
        migrations.CreateModel(
            name='Carourselkanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picha', models.ImageField(upload_to='pics', verbose_name='PICHA')),
            ],
            options={
                'verbose_name': 'PICHA YA KANDA ZETU',
                'verbose_name_plural': 'PICHA YA KANDA ZETU',
            },
        ),
        migrations.CreateModel(
            name='CarourselMahubiri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picha', models.ImageField(upload_to='pics', verbose_name='PICHA')),
            ],
            options={
                'verbose_name': 'PICHA YA MAHUBIRI',
                'verbose_name_plural': 'PICHA YA MAHUBIRI',
            },
        ),
        migrations.CreateModel(
            name='CarourselMaktaba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picha', models.ImageField(upload_to='pics', verbose_name='PICHA')),
            ],
            options={
                'verbose_name': 'PICHA YA MAKTABA',
                'verbose_name_plural': 'PICHA YA MAKTABA',
            },
        ),
        migrations.CreateModel(
            name='CarourselMatangazo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picha', models.ImageField(upload_to='pics', verbose_name='PICHA')),
            ],
            options={
                'verbose_name': 'PICHA YA MATANGAZO',
                'verbose_name_plural': 'PICHA YA MATANGAZO',
            },
        ),
        migrations.CreateModel(
            name='CarourselMatukio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picha', models.ImageField(upload_to='pics', verbose_name='PICHA')),
            ],
            options={
                'verbose_name': 'PICHA YA MATUKIO',
                'verbose_name_plural': 'PICHA YA MATUKIO',
            },
        ),
        migrations.CreateModel(
            name='CarourselRatiba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picha', models.ImageField(upload_to='pics', verbose_name='PICHA')),
            ],
            options={
                'verbose_name': 'PICHA YA RATIBA',
                'verbose_name_plural': 'PICHA YA RATIBA',
            },
        ),
        migrations.CreateModel(
            name='CarourselUwaka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picha', models.ImageField(upload_to='pics', verbose_name='PICHA')),
            ],
            options={
                'verbose_name': 'PICHA YA UWAKA',
                'verbose_name_plural': 'PICHA YA UWAKA',
            },
        ),
        migrations.CreateModel(
            name='CarourselViwawa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picha', models.ImageField(upload_to='pics', verbose_name='PICHA')),
            ],
            options={
                'verbose_name': 'PICHA YA VIWAWA',
                'verbose_name_plural': 'PICHA YA VIWAWA',
            },
        ),
        migrations.CreateModel(
            name='CarourselVyama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picha', models.ImageField(upload_to='pics', verbose_name='PICHA')),
            ],
            options={
                'verbose_name': 'PICHA ZA VYAMA VYETU',
                'verbose_name_plural': 'PICHA ZA VYAMA VYETU',
            },
        ),
        migrations.CreateModel(
            name='CarourselWawata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picha', models.ImageField(upload_to='pics', verbose_name='PICHA')),
            ],
            options={
                'verbose_name': 'PICHA YA WAWATA',
                'verbose_name_plural': 'PICHA YA WAWATA',
            },
        ),
        migrations.CreateModel(
            name='Ekaristi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picha', models.ImageField(null=True, upload_to='pics', verbose_name='PICHA')),
                ('maelezo', models.TextField(verbose_name='UJUMBE')),
            ],
            options={
                'verbose_name': 'EKARISTI TAKATIFU',
                'verbose_name_plural': 'EKARISTI TAKATIFU',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picha', models.ImageField(upload_to='pics', verbose_name='PICHA')),
                ('mwezi', models.CharField(max_length=3, verbose_name='MWEZI')),
                ('siku', models.CharField(max_length=2, verbose_name='SIKU')),
                ('title', models.CharField(max_length=255, verbose_name='TITLE')),
                ('tarehe_ya_tukio', models.DateField(verbose_name='TAREHE YA TUKIO')),
                ('location', models.CharField(max_length=255, verbose_name='SEHEMU YA TUKIO')),
                ('muda', models.CharField(max_length=255, verbose_name='MUDA')),
                ('maelezo', models.TextField(verbose_name='UJUMBE')),
            ],
            options={
                'verbose_name': 'MATUKIO',
                'verbose_name_plural': 'MATUKIO',
            },
        ),
        migrations.CreateModel(
            name='Faith',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imani', models.TextField(verbose_name='IMANI YA KANISA')),
            ],
            options={
                'verbose_name': 'IMANI YETU',
                'verbose_name_plural': 'IMANI YETU',
            },
        ),
        migrations.CreateModel(
            name='Give',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taarifa', models.TextField(verbose_name='UJUMBE')),
                ('kwa_simu', models.TextField(verbose_name='KWA SIMU')),
                ('kwa_benki', models.TextField(verbose_name='KWA BENKI')),
            ],
            options={
                'verbose_name': 'CHANGIA',
                'verbose_name_plural': 'CHANGIA',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('historia', models.TextField(verbose_name='HISTORIA YA KANISA')),
            ],
            options={
                'verbose_name': 'HISTORIA YETU',
                'verbose_name_plural': 'HISTORIA YETU',
            },
        ),
        migrations.CreateModel(
            name='Jumuiya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picha', models.ImageField(null=True, upload_to='pics', verbose_name='PICHA')),
                ('Jina_la_jumuiya', models.CharField(max_length=255, verbose_name='JINA LA JUMUIYA')),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'JUMUIYA ZETU',
                'verbose_name_plural': 'JUMUIYA ZETU',
            },
            bases=(main.mixins.SwahiliDateMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Kanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picha', models.ImageField(null=True, upload_to='pics', verbose_name='PICHA')),
                ('Jina_la_kanda', models.CharField(max_length=255, verbose_name='JINA LA KANDA')),
                ('tarehe', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'KANDA ZETU',
                'verbose_name_plural': 'KANDA ZETU',
            },
        ),
        migrations.CreateModel(
            name='Kipaimara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picha', models.ImageField(null=True, upload_to='pics', verbose_name='PICHA')),
                ('maelezo', models.TextField(verbose_name='UJUMBE')),
            ],
            options={
                'verbose_name': 'KIPAIMARA',
                'verbose_name_plural': 'KIPAIMARA',
            },
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarehe', models.DateField(verbose_name='TAREHE YA TUKIO')),
                ('title', models.CharField(max_length=255, verbose_name='TITLE')),
                ('location', models.CharField(max_length=255, verbose_name='SEHEMU YA TUKIO')),
            ],
            options={
                'verbose_name': 'MAKTABA YA PICHA',
                'verbose_name_plural': 'MAKTABA YA PICHA',
            },
        ),
        migrations.CreateModel(
            name='MakalaQuotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nukuu', models.TextField(verbose_name='NUKUU')),
                ('msemaji', models.CharField(max_length=50, verbose_name='MSEMAJI')),
                ('picha', models.ImageField(null=True, upload_to='pics', verbose_name='PICHA')),
            ],
            options={
                'verbose_name': 'NUKUU YA MAKALA',
                'verbose_name_plural': 'NUKUU YA MAKALA',
            },
        ),
        migrations.CreateModel(
            name='Mapadri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picha', models.ImageField(upload_to='pics', verbose_name='PICHA')),
                ('cheo', models.CharField(max_length=255, verbose_name='CHEO')),
                ('jina', models.CharField(max_length=40, verbose_name='JINA LA PADRI')),
                ('maelezo', models.CharField(max_length=50, verbose_name='MAELEZO')),
            ],
            options={
                'verbose_name': 'MAPADRI',
                'verbose_name_plural': 'MAPADRI',
            },
        ),
        migrations.CreateModel(
            name='Masomo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picha', models.ImageField(upload_to='pics', verbose_name='PICHA')),
                ('somo_la', models.CharField(max_length=20, verbose_name='SOMO LA')),
                ('limetoka', models.CharField(max_length=20, verbose_name='LIMETOKA')),
            ],
            options={
                'verbose_name': 'MASOMO YA LEO',
                'verbose_name_plural': 'MASOMO YA LEO',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taarifa', models.TextField(verbose_name='UJUMBE')),
                ('whatsapp_url', models.URLField(verbose_name='WHATSAPP LINK')),
                ('email_url', models.EmailField(max_length=254, verbose_name='BARUA PEPE')),
                ('phone_number', models.CharField(max_length=30, verbose_name='NAMBA YA SIMU')),
            ],
            options={
                'verbose_name': 'TUMA UJUMBE',
                'verbose_name_plural': 'TUMA UJUMBE',
            },
        ),
        migrations.CreateModel(
            name='Mubashara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picha', models.ImageField(null=True, upload_to='pics', verbose_name='PICHA')),
                ('taarifa', models.TextField(verbose_name='UJUMBE')),
                ('tarehe', models.DateField(verbose_name='TAREHE')),
                ('weekday', models.CharField(max_length=255, verbose_name='SIKU YA JUMA')),
                ('muda', models.CharField(max_length=255, verbose_name='MUDA')),
                ('link_url', models.URLField(verbose_name='LINK')),
            ],
            options={
                'verbose_name': 'LIVE MATANGAZO',
                'verbose_name_plural': 'LIVE MATANGAZO',
            },
        ),
        migrations.CreateModel(
            name='Muda_wa_ibada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siku_za_juma', models.CharField(max_length=255, verbose_name='SIKU ZA JUMA')),
                ('misa_ya_kwanza', models.CharField(max_length=255, verbose_name='MISA YA KWANZA')),
                ('misa_ya_pili', models.CharField(max_length=255, verbose_name='MISA YA PILI')),
                ('misa_ya_watoto', models.CharField(max_length=255, verbose_name='MISA YA WATOTO')),
            ],
            options={
                'verbose_name': 'MUDA WA IBADA',
                'verbose_name_plural': 'MUDA WA IBADA',
            },
        ),
        migrations.CreateModel(
            name='Muda_wa_Maungamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ijumaa', models.CharField(max_length=255)),
                ('jumamosi', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'MUDA WA MAUNGAMO',
                'verbose_name_plural': 'MUDA WA MAUNGAMO',
            },
        ),
        migrations.CreateModel(
            name='Ndoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picha', models.ImageField(null=True, upload_to='pics', verbose_name='PICHA')),
                ('maelezo', models.TextField(verbose_name='UJUMBE')),
            ],
            options={
                'verbose_name': 'NDOA',
                'verbose_name_plural': 'NDOA',
            },
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picha', models.ImageField(upload_to='pics', verbose_name='PICHA')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('title', models.CharField(max_length=50, verbose_name='TITLE')),
                ('video_url', models.URLField(verbose_name='VIDEO LINK')),
                ('maelezo', models.TextField(verbose_name='UJUMBE')),
            ],
            options={
                'verbose_name': 'PODIKASITI',
                'verbose_name_plural': 'PODIKASITI',
            },
            bases=(main.mixins.SwahiliDateMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PodikasitiMainPageVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='videos/', verbose_name='VIDEO')),
                ('picha', models.ImageField(null=True, upload_to='pics', verbose_name='PICHA')),
            ],
            options={
                'verbose_name': 'PODIKASITI PIC & VIDEO',
                'verbose_name_plural': 'PODIKASITI PIC & VIDEO',
            },
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sera', models.TextField(verbose_name='SERA YA KANISA')),
            ],
            options={
                'verbose_name': 'SERA YA FARAGHA',
                'verbose_name_plural': 'SERA YA FARAGHA',
            },
        ),
        migrations.CreateModel(
            name='Ratiba_za_ofisini',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siku_za_juma', models.CharField(max_length=255, verbose_name='SIKU ZA JUMA')),
                ('jumapili', models.CharField(max_length=255, verbose_name='JUMAPILI')),
            ],
            options={
                'verbose_name': 'RATIBA ZA KANISANI',
                'verbose_name_plural': 'RATIBA ZA KANISANI',
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('masharti', models.TextField(verbose_name='SHERIA NA MASHARTI')),
            ],
            options={
                'verbose_name': 'SHERIA NA MASHARTI',
                'verbose_name_plural': 'SHERIA NA MASHARTI',
            },
        ),
        migrations.CreateModel(
            name='Sermon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picha', models.ImageField(upload_to='pics', verbose_name='PICHA')),
                ('weekday', models.CharField(blank=True, editable=False, max_length=255, verbose_name='SIKU YA JUMA')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('somo_la_kwanza', models.CharField(max_length=255, verbose_name='SOMO LA KWANZA')),
                ('somo_la_pili', models.CharField(max_length=255, verbose_name='SOMO LA PILI')),
                ('injili', models.CharField(max_length=255, verbose_name='INJILI')),
                ('tafakari', models.TextField(verbose_name='TAFAKARI')),
            ],
            options={
                'verbose_name': 'MAHUBIRI',
                'verbose_name_plural': 'MAHUBIRI',
            },
            bases=(main.mixins.SwahiliDateMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Toba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picha', models.ImageField(null=True, upload_to='pics', verbose_name='PICHA')),
                ('maelezo', models.TextField(verbose_name='UJUMBE')),
            ],
            options={
                'verbose_name': 'TOBA',
                'verbose_name_plural': 'TOBA',
            },
        ),
        migrations.CreateModel(
            name='Ubatizo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picha', models.ImageField(null=True, upload_to='pics', verbose_name='PICHA')),
                ('maelezo', models.TextField(verbose_name='UJUMBE')),
            ],
            options={
                'verbose_name': 'UBATIZO',
                'verbose_name_plural': 'UBATIZO',
            },
        ),
        migrations.CreateModel(
            name='Upako_wa_Wagonjwa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picha', models.ImageField(null=True, upload_to='pics', verbose_name='PICHA')),
                ('maelezo', models.TextField(verbose_name='UJUMBE')),
            ],
            options={
                'verbose_name': 'UPAKO WA WAGONJWA',
                'verbose_name_plural': 'UPAKO WA WAGONJWA',
            },
        ),
        migrations.CreateModel(
            name='Uwaka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('maelezo', models.TextField(verbose_name='UJUMBE')),
            ],
            options={
                'verbose_name': 'UWAKA',
                'verbose_name_plural': 'UWAKA',
            },
            bases=(main.mixins.SwahiliDateMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Viongozi_wa_Jumuiya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picha', models.ImageField(upload_to='pics', verbose_name='PICHA')),
                ('cheo', models.CharField(max_length=255, verbose_name='CHEO')),
                ('jina', models.CharField(max_length=40, verbose_name='JINA LA KIONGOZI')),
                ('Jina_la_jumuiya', models.CharField(max_length=60, verbose_name='JINA LA JUMUIYA')),
            ],
            options={
                'verbose_name': 'VIONGOZI WA JUMUIYA',
                'verbose_name_plural': 'VIONGOZI WA JUMUIYA',
            },
        ),
        migrations.CreateModel(
            name='Viongozi_wa_kanisani',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picha', models.ImageField(upload_to='pics', verbose_name='PICHA')),
                ('cheo', models.CharField(max_length=255, verbose_name='CHEO')),
                ('jina', models.CharField(max_length=40, verbose_name='JINA LA KIONGOZI')),
                ('chama', models.CharField(max_length=60, verbose_name='JINA LA CHAMA')),
            ],
            options={
                'verbose_name': 'VIONGOZI WA KANISANI',
                'verbose_name_plural': 'VIONGOZI WA KANISANI',
            },
        ),
        migrations.CreateModel(
            name='Viwawa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('maelezo', models.TextField(verbose_name='UJUMBE')),
            ],
            options={
                'verbose_name': 'VIWAWA',
                'verbose_name_plural': 'VIWAWA',
            },
            bases=(main.mixins.SwahiliDateMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Vyama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picha', models.ImageField(null=True, upload_to='pics', verbose_name='PICHA')),
                ('Jina_la_chama', models.CharField(max_length=255, verbose_name='JINA LA CHAMA')),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'VYAMA VYETU',
                'verbose_name_plural': 'VYAMA VYETU',
            },
            bases=(main.mixins.SwahiliDateMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Wawata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('maelezo', models.TextField(verbose_name='UJUMBE')),
            ],
            options={
                'verbose_name': 'WAWATA',
                'verbose_name_plural': 'WAWATA',
            },
            bases=(main.mixins.SwahiliDateMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AnnouncementDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('upload_file', models.FileField(null=True, upload_to='documents')),
                ('matangazo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='main.announcement')),
            ],
        ),
        migrations.CreateModel(
            name='BlogDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('upload_file', models.FileField(null=True, upload_to='documents')),
                ('matangazo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='main.blog')),
            ],
        ),
        migrations.CreateModel(
            name='EkaristiDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('upload_file', models.FileField(upload_to='documents')),
                ('ekaristi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='main.ekaristi')),
            ],
        ),
        migrations.CreateModel(
            name='EventDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('upload_file', models.FileField(null=True, upload_to='documents')),
                ('matangazo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='main.event')),
            ],
        ),
        migrations.CreateModel(
            name='Jumuiya_page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('maelezo', models.TextField(verbose_name='TANGAZO')),
                ('jumuiya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='main.jumuiya')),
            ],
            options={
                'verbose_name': 'JUMUIYA (MATANGAZO)',
                'verbose_name_plural': 'JUMUIYA (MATANGAZO)',
            },
            bases=(main.mixins.SwahiliDateMixin, models.Model),
        ),
        migrations.CreateModel(
            name='JumuiyaDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('upload_file', models.FileField(null=True, upload_to='documents')),
                ('matangazo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='main.jumuiya_page')),
            ],
        ),
        migrations.CreateModel(
            name='Kanda_page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarehe', models.DateField(auto_now_add=True, null=True)),
                ('maelezo', models.TextField(verbose_name='TANGAZO')),
                ('kanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chama', to='main.kanda')),
            ],
            options={
                'verbose_name': 'KANDA (MATANGAZO)',
                'verbose_name_plural': 'KANDA (MATANGAZO)',
            },
        ),
        migrations.CreateModel(
            name='KandaDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('upload_file', models.FileField(null=True, upload_to='documents')),
                ('matangazo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='main.kanda_page')),
            ],
        ),
        migrations.CreateModel(
            name='KipaimaraDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('upload_file', models.FileField(upload_to='documents')),
                ('kipaimara', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='main.kipaimara')),
            ],
        ),
        migrations.CreateModel(
            name='NdoaDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('upload_file', models.FileField(upload_to='documents')),
                ('ndoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='main.ndoa')),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picha', models.ImageField(upload_to='pics')),
                ('libray', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.library')),
            ],
        ),
        migrations.CreateModel(
            name='Resetpassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reset_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_when', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'RESET PASSWORD',
                'verbose_name_plural': 'RESET PASSWORD',
            },
        ),
        migrations.CreateModel(
            name='UbatizoDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('upload_file', models.FileField(upload_to='documents')),
                ('ubatizo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='main.ubatizo')),
            ],
        ),
        migrations.CreateModel(
            name='UwakaDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('upload_file', models.FileField(null=True, upload_to='documents')),
                ('matangazo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='main.uwaka')),
            ],
        ),
        migrations.CreateModel(
            name='ViwawaDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('upload_file', models.FileField(null=True, upload_to='documents')),
                ('matangazo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='main.viwawa')),
            ],
        ),
        migrations.CreateModel(
            name='Vyama_page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('maelezo', models.TextField(verbose_name='TANGAZO')),
                ('vyama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chama', to='main.vyama')),
            ],
            options={
                'verbose_name': 'VYAMA (MATANGAZO)',
                'verbose_name_plural': 'VYAMA (MATANGAZO)',
            },
            bases=(main.mixins.SwahiliDateMixin, models.Model),
        ),
        migrations.CreateModel(
            name='VyamaDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('upload_file', models.FileField(null=True, upload_to='documents')),
                ('matangazo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='main.vyama_page')),
            ],
        ),
        migrations.CreateModel(
            name='WawataDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('upload_file', models.FileField(null=True, upload_to='documents')),
                ('matangazo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='main.wawata')),
            ],
        ),
    ]
