# Generated by Django 5.1.6 on 2025-03-24 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarourselUongozi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picha', models.ImageField(upload_to='pics', verbose_name='PICHA')),
            ],
            options={
                'verbose_name': 'PICHA YA UONGOZI',
                'verbose_name_plural': 'PICHA YA UONGOZI',
            },
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'USER MANAGEMENT', 'verbose_name_plural': 'USER MANAGEMENT'},
        ),
    ]
