# Generated by Django 5.1.6 on 2025-03-20 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='tarehe_ya_tukio',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='kanda',
            old_name='tarehe',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='kanda_page',
            old_name='tarehe',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='library',
            old_name='tarehe',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='mubashara',
            old_name='tarehe',
            new_name='created_at',
        ),
    ]
