# Generated by Django 5.1.6 on 2025-03-24 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_carourseluongozi_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uwaka',
            name='maelezo',
            field=models.TextField(verbose_name='TANGAZO'),
        ),
        migrations.AlterField(
            model_name='viwawa',
            name='maelezo',
            field=models.TextField(verbose_name='TANGAZO'),
        ),
        migrations.AlterField(
            model_name='wawata',
            name='maelezo',
            field=models.TextField(verbose_name='TANGAZO'),
        ),
    ]
