# Generated by Django 5.1.6 on 2025-03-21 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_tarehe_ya_tukio_event_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masomo',
            name='somo_la',
            field=models.CharField(max_length=20, verbose_name='SOMO'),
        ),
    ]
