# Generated by Django 5.1.6 on 2025-03-24 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_uwaka_maelezo_alter_viwawa_maelezo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselPodikasiti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picha', models.ImageField(null=True, upload_to='pics', verbose_name='PICHA')),
            ],
            options={
                'verbose_name': 'PODIKASITI PICHA',
                'verbose_name_plural': 'PODIKASITI PICHA',
            },
        ),
        migrations.DeleteModel(
            name='PodikasitiMainPageVideo',
        ),
    ]
