# Generated by Django 5.1.6 on 2025-03-25 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_carouselpodikasiti_delete_podikasitimainpagevideo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carouselpodikasiti',
            options={'verbose_name': 'PICHA YA PODIKASITI', 'verbose_name_plural': 'PICHA YA PODIKASITI'},
        ),
        migrations.AlterField(
            model_name='mubashara',
            name='link_url',
            field=models.URLField(verbose_name='YOUTUBE LINK'),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='maelezo',
            field=models.TextField(max_length=30, verbose_name='UJUMBE'),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='video_url',
            field=models.URLField(verbose_name='YOUTUBE LINK'),
        ),
    ]
