# Generated by Django 5.1.6 on 2025-03-25 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_carouselpodikasiti_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='maelezo',
            field=models.TextField(max_length=100, verbose_name='UJUMBE'),
        ),
    ]
