# Generated by Django 5.1.6 on 2025-03-25 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_podcast_maelezo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='maelezo',
            field=models.TextField(max_length=255, verbose_name='UJUMBE'),
        ),
    ]
