# Generated by Django 5.1.6 on 2025-03-25 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_podcast_maelezo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mubashara',
            name='created_at',
            field=models.DateField(blank=True, null=True, verbose_name='TAREHE'),
        ),
        migrations.AlterField(
            model_name='mubashara',
            name='link_url',
            field=models.URLField(blank=True, null=True, verbose_name='YOUTUBE LINK'),
        ),
        migrations.AlterField(
            model_name='mubashara',
            name='muda',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='MUDA'),
        ),
        migrations.AlterField(
            model_name='mubashara',
            name='weekday',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='SIKU YA JUMA'),
        ),
    ]
