# Generated by Django 5.1.6 on 2025-03-25 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_mubashara_created_at_alter_mubashara_link_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mubashara',
            name='muda',
            field=models.CharField(blank=True, default='Hamna', max_length=255, null=True, verbose_name='MUDA'),
        ),
        migrations.AlterField(
            model_name='mubashara',
            name='weekday',
            field=models.CharField(blank=True, default='Hamna', max_length=255, null=True, verbose_name='SIKU YA JUMA'),
        ),
    ]
