# Generated by Django 5.1.6 on 2025-03-25 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_mubashara_muda_alter_mubashara_weekday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mubashara',
            name='muda',
            field=models.CharField(blank=True, default='Hamna', max_length=255, verbose_name='MUDA'),
        ),
        migrations.AlterField(
            model_name='mubashara',
            name='weekday',
            field=models.CharField(blank=True, default='Hamna', max_length=255, verbose_name='SIKU YA JUMA'),
        ),
    ]
