# Generated by Django 5.1.6 on 2025-03-26 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_mubashara_muda_alter_mubashara_weekday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makalaquotation',
            name='nukuu',
            field=models.CharField(max_length=200, verbose_name='NUKUU'),
        ),
    ]
