# Generated by Django 5.1.6 on 2025-03-26 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_makalaquotation_nukuu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makalaquotation',
            name='nukuu',
            field=models.TextField(max_length=255, verbose_name='NUKUU'),
        ),
    ]
