# Generated by Django 5.1.6 on 2025-04-08 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_makalaquotation_nukuu'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uwaka',
            options={'verbose_name': 'UWAKA (MATANGAZO)', 'verbose_name_plural': 'UWAKA (MATANGAZO)'},
        ),
        migrations.AlterModelOptions(
            name='viwawa',
            options={'verbose_name': 'VIWAWA (MATANGAZO)', 'verbose_name_plural': 'VIWAWA (MATANGAZO)'},
        ),
        migrations.AlterModelOptions(
            name='wawata',
            options={'verbose_name': 'WAWATA (MATANGAZO)', 'verbose_name_plural': 'WAWATA (MATANGAZO)'},
        ),
    ]
