# Generated by Django 5.1.6 on 2025-06-13 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_uwaka_options_alter_viwawa_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='email_url',
        ),
        migrations.RemoveField(
            model_name='message',
            name='whatsapp_url',
        ),
    ]
