# Generated by Django 5.1.6 on 2025-06-13 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_message_email_url_remove_message_whatsapp_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='maelezo',
            field=models.TextField(verbose_name='UJUMBE'),
        ),
    ]
