# Generated by Django 5.1.6 on 2025-06-15 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_paymenttransaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymenttransaction',
            options={'verbose_name': 'MIAMALA YA MALIPO', 'verbose_name_plural': 'MIAMALA YA MALIPO'},
        ),
    ]
