# Generated by Django 5.1.6 on 2025-06-15 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_paymenttransaction_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='give',
            name='kwa_simu',
        ),
    ]
