# Generated by Django 5.1.6 on 2025-06-15 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_remove_give_kwa_simu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='give',
            name='kwa_benki',
        ),
    ]
