# Generated by Django 5.1.6 on 2025-06-17 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_remove_give_kwa_benki'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='operator',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
